# 连接配置
sql:
  # 类型，不区分大小写
  # sqlite - 本地
  # mysql - 远程
  type: sqlite
  # 地址
  host: localhost
  # 端口
  port: 3306
  # 用户名
  user: root
  # 密码
  password: root
  # 数据库
  database: minecraft
  # 表名
  table: BilibiliVideo